# Numpy

[NumPy](https://numpy.org/) is the fundamental package for scientific computing with Python.

### Installation:

<div class="alert alert-block alert-warning">
$ pip install numpy
</div>

or

<div class="alert alert-block alert-warning">
$ conda install numpy
</div>

In [1]:
! pip install numpy

In [1]:
import numpy as np

In [2]:
N = 1000000
my_arr = np.arange(N)
my_list = [i for i in range(N)]

In [3]:
%time for _ in range(10): my_arr2 = 2*my_arr

CPU times: user 15.9 ms, sys: 11.6 ms, total: 27.5 ms
Wall time: 27.6 ms


In [4]:
%time for _ in range(10): my_list2 = [2*x for x in my_list]

CPU times: user 310 ms, sys: 54.2 ms, total: 365 ms
Wall time: 366 ms


In [5]:
366/27.6

13.26086956521739

## Basics:
___

One of the most commonly used functions of NumPy are *NumPy arrays*: The essential difference between lists and NumPy arrays is functionality and speed. lists give you basic operation, but NumPy adds FFTs, convolutions, fast searching, basic statistics, linear algebra, histograms, etc.

The most important difference for data science is the ability to do **element-wise calculations** with *NumPy* arrays.

`axis 0` always refers to row <br>
`axis 1` always refers to column

+ `np.array([1,2,3])`
+ `np.array([(1,2,3),(4,5,6)])`
+ `np.arange(start,stop,step)`

**Placeholders**:
- `np.linspace(0,2,9)`
- `np.zeros((1,2))`
- `np.ones((1,2))`
- `np.random.random((5,5))`
- `np.empty((2,2))`
- `np.full((3, 3), 7)`

In [11]:
arr_1d = np.array([1, 2, 3, 4, 5])

In [10]:
type(arr_1d)

numpy.ndarray

In [15]:
arr_1d[0], arr_1d[3], arr_1d[-1], arr_1d[-2]

(1, 4, 5, 4)

In [25]:
arr_2d = np.array([[1, 2, 3, 4],
                   [-1, 0, 1, 0]])

In [19]:
arr_2d[0][2], arr_2d[0, 2]

(3, 3)

In [20]:
arr_2d.shape

(2, 4)

In [21]:
arr_3d = np.array([[[1, 2, 3, 4],
                    [5, 6, 7, 8]],
                   
                   [[-1, -2, -3, -4],
                    [-5, -6, -7, -8]],
                   
                   [[11, 12, 13, 14],
                    [15, 16, 17, 18]]])

In [22]:
arr_3d.shape

(3, 2, 4)

In [26]:
arr_3d[1, 0, 2]

-3

In [29]:
arr_3d[2, :, :]

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [31]:
arr_3d[:, 1, :]

array([[ 5,  6,  7,  8],
       [-5, -6, -7, -8],
       [15, 16, 17, 18]])

In [32]:
arr_3d[:, :, 0]

array([[ 1,  5],
       [-1, -5],
       [11, 15]])

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [38]:
np.arange(-0.5, 1.1, 0.1)

array([-5.00000000e-01, -4.00000000e-01, -3.00000000e-01, -2.00000000e-01,
       -1.00000000e-01, -1.11022302e-16,  1.00000000e-01,  2.00000000e-01,
        3.00000000e-01,  4.00000000e-01,  5.00000000e-01,  6.00000000e-01,
        7.00000000e-01,  8.00000000e-01,  9.00000000e-01,  1.00000000e+00])

In [42]:
np.linspace(-0.5, 1, 16)

array([-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,
        0.6,  0.7,  0.8,  0.9,  1. ])

In [49]:
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
np.full((3, 4), -7)

array([[-7, -7, -7, -7],
       [-7, -7, -7, -7],
       [-7, -7, -7, -7]])

In [46]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.random.random((4, 4))

array([[0.58903572, 0.78590464, 0.37887953, 0.87531792],
       [0.16664414, 0.65922083, 0.67297589, 0.75300768],
       [0.09754899, 0.57957748, 0.3717744 , 0.30291825],
       [0.2485746 , 0.38851757, 0.83948559, 0.90271738]])

In [52]:
np.random.uniform(0, 4, (2, 5))

array([[1.31999014, 2.47239128, 0.99578403, 1.26212999, 3.75389943],
       [0.4924544 , 0.03912071, 1.02008476, 3.1409131 , 2.15497137]])

In [53]:
np.random.normal(0, 1, (3, 3))

array([[-1.60075949,  2.92272174, -0.09821871],
       [-1.42681597,  1.18025689,  0.53999068],
       [-0.71931946, -0.04686306, -0.32423992]])

In [62]:
np.random.randint(0, 20, (34,))

array([ 0, 17, 17, 16,  7, 18, 16,  1, 18, 18, 18,  4, 12,  1,  6,  7,  4,
       16, 14, 15, 14, 16, 13,  3,  2,  6, 17,  9, 12, 17,  7,  6,  9, 12])

In [34]:
# np.int8, np.int16, np.int32, np.int64
# np.float16, np.float32, np.float64, np.float128
# np.uint8, np.uint16, np.uint32, np.uint64

In [69]:
b = np.random.randint(0, 20, (34,), dtype=np.uint8)

In [70]:
b.dtype

dtype('uint8')

In [41]:
m = np.random.randint(0, 10, (4, 4))

In [5]:
m

array([[6, 1, 8, 4],
       [2, 2, 3, 6],
       [2, 1, 9, 4],
       [7, 2, 2, 6]])

In [4]:
2*m

array([[12,  2, 16,  8],
       [ 4,  4,  6, 12],
       [ 4,  2, 18,  8],
       [14,  4,  4, 12]])

In [6]:
m**2

array([[36,  1, 64, 16],
       [ 4,  4,  9, 36],
       [ 4,  1, 81, 16],
       [49,  4,  4, 36]])

In [7]:
np.sqrt(m)

array([[2.44948974, 1.        , 2.82842712, 2.        ],
       [1.41421356, 1.41421356, 1.73205081, 2.44948974],
       [1.41421356, 1.        , 3.        , 2.        ],
       [2.64575131, 1.41421356, 1.41421356, 2.44948974]])

In [8]:
2**m

array([[ 64,   2, 256,  16],
       [  4,   4,   8,  64],
       [  4,   2, 512,  16],
       [128,   4,   4,  64]])

In [10]:
m1 = np.random.randint(0, 10, (4, 2))
m2 = np.random.randint(0, 10, (2, 5))

In [13]:
np.dot(m1, m2)

array([[12, 19,  3, 25, 17],
       [24, 30,  6, 30,  6],
       [ 0, 12,  0, 30, 42],
       [ 0, 12,  0, 30, 42]])

In [14]:
m1.dot(m2)

array([[12, 19,  3, 25, 17],
       [24, 30,  6, 30,  6],
       [ 0, 12,  0, 30, 42],
       [ 0, 12,  0, 30, 42]])

In [16]:
m1 @ m2 # the most efficient one

array([[12, 19,  3, 25, 17],
       [24, 30,  6, 30,  6],
       [ 0, 12,  0, 30, 42],
       [ 0, 12,  0, 30, 42]])

In [28]:
s = np.eye(m.shape[0])

for i in range(3): s = s @ m

In [29]:
s

array([[1404.,  433., 2079., 1512.],
       [1024.,  303., 1260., 1034.],
       [1136.,  358., 1663., 1242.],
       [1374.,  402., 1807., 1390.]])

In [31]:
np.linalg.matrix_power(m, 3)

array([[1404,  433, 2079, 1512],
       [1024,  303, 1260, 1034],
       [1136,  358, 1663, 1242],
       [1374,  402, 1807, 1390]])

In [19]:
m1.transpose()

array([[2, 0, 6, 6],
       [3, 6, 0, 0]])

In [20]:
m1.T

array([[2, 0, 6, 6],
       [3, 6, 0, 0]])

In [21]:
np.trace(m)

23

In [32]:
m

array([[6, 1, 8, 4],
       [2, 2, 3, 6],
       [2, 1, 9, 4],
       [7, 2, 2, 6]])

In [23]:
m > 5

array([[ True, False,  True, False],
       [False, False, False,  True],
       [False, False,  True, False],
       [ True, False, False,  True]])

In [33]:
m[m>5] += 2

In [34]:
m

array([[ 8,  1, 10,  4],
       [ 2,  2,  3,  8],
       [ 2,  1, 11,  4],
       [ 9,  2,  2,  8]])

## Array:

+ `array.shape`	
+ `len(array)`
+ `array.ndim	`
+ `array.size`	
+ `array.dtype`	
+ `array.astype(type)`	


+ `np.copy(array)`	
+ `other = array.copy()`	
+ `array.sort()`
+ `array.sort(axis=0)`

In [35]:
m.shape

(4, 4)

In [36]:
m.ndim

2

In [37]:
m.size

16

In [38]:
m.dtype

dtype('int64')

In [42]:
m3 = m.copy()

m3[:, 0] = -1

In [43]:
m

array([[6, 0, 4, 1],
       [8, 0, 5, 3],
       [0, 7, 1, 9],
       [0, 4, 5, 6]])

In [44]:
np.reshape(m, (2, 8))

array([[6, 0, 4, 1, 8, 0, 5, 3],
       [0, 7, 1, 9, 0, 4, 5, 6]])

In [45]:
b = m.astype(np.int8)

In [46]:
b.dtype

dtype('int8')

In [55]:
np.random.seed(10)

In [58]:
x = np.random.randint(0, 10, (10, 5), )

In [59]:
x

array([[4, 7, 8, 8, 2],
       [6, 2, 8, 8, 6],
       [6, 5, 6, 0, 0],
       [6, 9, 1, 8, 9],
       [1, 2, 8, 9, 9],
       [5, 0, 2, 7, 3],
       [0, 4, 2, 0, 3],
       [3, 1, 2, 5, 9],
       [0, 1, 0, 1, 9],
       [0, 9, 2, 1, 1]])

In [51]:
x.mean()

3.88

In [53]:
x.mean(axis=0)

array([4.2, 3.3, 3.1, 4.7, 4.1])

In [54]:
x.mean(axis=1)

array([1.8, 4.2, 2.4, 5.8, 3.8, 5. , 2.6, 4.4, 3.2, 5.6])

In [60]:
x.sum()

208

In [61]:
x.sum(axis=0)

array([31, 40, 39, 47, 51])

In [62]:
x.sum(axis=1)

array([29, 30, 17, 33, 29, 17,  9, 20, 11, 13])

In [63]:
x.std()

3.264107841355736

## Linerar algebra

In [70]:
v = np.random.randint(-10, 10, (10, ))

In [75]:
np.sum(np.abs(v)), np.linalg.norm(v, 1)

(40, 40.0)

In [80]:
np.sqrt(np.sum(v**2)), np.linalg.norm(v, 2)

(14.7648230602334, 14.7648230602334)

In [84]:
(np.sum(np.abs(v)**3))**(1/3), np.linalg.norm(v, 3)

(11.318511959629506, 11.318511959629506)

In [86]:
np.linalg.det(m)

321.9999999999998

In [ ]:
# solve A x = b

In [90]:
A = np.random.randint(0, 20, (6, 6))
b = np.random.randint(-10, 10, (6, ))

In [91]:
A

array([[12, 17,  5, 18, 19,  5],
       [12,  6,  8, 16, 10,  4],
       [19,  9,  3,  3, 16, 11],
       [ 9, 18, 19,  9, 17, 10],
       [ 4,  0,  0, 10,  8, 17],
       [13,  3,  0,  0,  6,  5]])

In [92]:
b

array([  5,  -3, -10, -10,   8,  -8])

In [94]:
x_1 = np.linalg.inv(A) @ b

In [95]:
x_2 = np.linalg.solve(A, b)

In [96]:
x_1

array([-0.78698448,  0.34400955, -0.92337586,  0.68207309, -0.02027342,
        0.26408202])

In [97]:
x_2

array([-0.78698448,  0.34400955, -0.92337586,  0.68207309, -0.02027342,
        0.26408202])

In [98]:
x_1 == x_2

array([False, False, False, False, False, False])

In [99]:
x_1 - x_2

array([ 6.66133815e-16, -4.99600361e-16,  1.11022302e-16,  1.11022302e-16,
       -3.92047506e-16,  1.66533454e-16])

In [105]:
np.isclose(x_1, x_2)

array([ True,  True,  True,  True,  True,  True])

In [113]:
np.isclose(A @ np.linalg.inv(A), np.eye(6), atol=1e-17)

array([[ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False,  True, False],
       [False,  True, False, False, False,  True]])

In [122]:
a = 1.52345

In [126]:
np.ceil(100*a)/100, np.floor(100*a)/100, np.round(100*a)/100

(1.53, 1.52, 1.52)

In [127]:
np.round(a, decimals=3)

1.523